# Stream type: match | showcase | other
type: "showcase"

# q / ro64 / ro32 / ro16 / qf / sf / f / gf
mappool_name: "q"

# For match streaming
match_code: ""

# For showcase streaming
schedule: "2025-09-07T21:00:00+00:00"
title: ""
